/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RbkcrYR76E9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogTrigger, DialogContent, DialogClose } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <Dialog defaultOpen>
      <DialogTrigger asChild>
        <Button variant="outline">Show Alert</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[400px] w-full p-6 bg-background rounded-lg shadow-lg">
        <div className="flex flex-col items-center justify-center gap-4">
          <div className="space-y-2 text-center">
            <h3 className="text-xl font-bold">Important Message</h3>
            <p className="text-muted-foreground">
              This is an important alert that requires your attention. Please review the details carefully.
            </p>
          </div>
          <div>
            <Button variant="ghost" className="w-full">
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
